### ISSUE TITLE
Hi，请问这个CMONGO相对传统的MONGODB有哪些优势？有相关说明吗？

### ISSUE THREAD

**Issue by imfht** [Tencent/CMONGO#1]
RT

**Comment by demonyang** [comment]
CMONGO是腾讯云MongoDB的内核版本，基于原生3.2.10，我们团队做了很多自己的优化，第一期开源的包括支持动态 resize oplog、WT引擎支持hotBackup、连接认证随机数优化，后续慢慢会开源更多的特性。

**Comment by y123456yz** [comment]
@demonyang   能否文档详细说明下，还有就是想知道这个版本如何与官方保持同步，例如3.2以后版本对wiredtiger做了很多优化，是否会实时进行官方合并，同步优化。

你们做的优化要是能有文档详细说明就更好了。期待回复，谢谢。
